erDiagram

    topic {
        string title
        string description
    }

    article {
        string title
        text content
        date created_at
        date updated_at
    }

    comment {
        datetime created_at
        text message
    }

    article ||--|{ comment: contains
    topic }|--o{ article: contains
    topic }o--o{ user: prefers
    user }|--|| article: author
    user }|--|| comment: author
